GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Some Title",
  "author": "Dan Lowery",
  "url": "https://blogs.com/221",
  "likes": 999
}