GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/69a0e03d61b592b0b7ddfac5

###
GET http://localhost:3001/info

###
DELETE http://localhost:3001/api/persons/69a352dc400ee8e0cae7e2f7

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{ 
  "name": "Pavlo Bilousov", 
  "number": "12-43-234345"
}

###
GET https://phonebook-backend-bold-water-2846.fly.dev/api/persons