GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/69a360e8aa06da2c3aa66d61

###
GET http://localhost:3001/info

###
DELETE http://localhost:3001/api/persons/69a35ff6aa06da2c3aa66d4a

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{ 
  "name": "Dam Abraamov", 
  "number": "12-43-234345"
}

###
PUT http://localhost:3001/api/persons/69a36000aa06da2c3aa66d4c
Content-Type: application/json

{ 
  "number": "999"
}

###
GET https://phonebook-backend-bold-water-2846.fly.dev/api/persons