GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/3

###
GET http://localhost:3001/info

###
DELETE http://localhost:3001/api/persons/1

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{ 
  "name": "Da Abramov", 
  "number": "12-43-234345"
}

###
GET https://phonebook-backend-bold-water-2846.fly.dev/api/persons